import { z } from "zod";
import type { TradeRecord, UserData, UserDataV1 } from "../domain/models";
import { calculateAvailableCash, calculatePurchaseCost, calculateRealizedPnL, calculateSaleProceeds, roundMoney } from "../domain/portfolio";

export const USER_DATA_STORAGE_KEY = "stockpilot-user-data-v2";
export const LEGACY_USER_DATA_STORAGE_KEY = "stockpilot-user-data-v1";
const THEME_STORAGE_KEY = "stockpilot-theme";
const ticker=z.enum(["AAPL","MSFT","NVDA","AMZN","TSLA"]);
const checklist=z.object({why:z.string(),holding:z.string(),invalidation:z.string(),maxLoss:z.string(),weight:z.string(),driver:z.string(),event:z.string(),target:z.string(),exit:z.string()});
const warning=z.object({code:z.enum(["MISSING_INVALIDATION","MISSING_EXIT_PLAN","OVERSIZED_POSITION","HIGH_LOSS_LIMIT","MAJOR_EVENT","EVENT_UNKNOWN","MOMENTUM_CHASING","INVALID_NUMBER","INVALID_TARGET","INSUFFICIENT_CASH","ZERO_SHARES"]),severity:z.enum(["serious","general"]),message:z.string()});
const watchlist=z.object({ticker,target:z.number().finite().nonnegative(),reason:z.string(),status:z.enum(["Researching","Watching","Ready to Buy","Avoiding"])});
const v1Trade=z.object({id:z.number().int(),ticker,buyPrice:z.number().finite().positive(),shares:z.number().finite().positive(),date:z.string(),target:z.number().finite(),maxLoss:z.number().finite(),thesis:z.string(),invalidation:z.string(),holding:z.string(),closed:z.boolean().optional(),sellPrice:z.number().finite().optional()});
const trade=z.object({id:z.number().int(),ticker,buyPrice:z.number().finite().positive(),shares:z.number().finite().positive(),date:z.string(),intendedWeightPercent:z.number().finite().min(0).max(100),actualWeightPercentAtEntry:z.number().finite().min(0).max(100),buyDriver:z.string(),upcomingEventStatus:z.string(),targetPrice:z.number().finite().positive(),maximumLossPercent:z.number().finite().positive().max(100),thesis:z.string(),invalidationCondition:z.string(),exitPlan:z.string(),expectedHoldingPeriod:z.string(),checklistScoreAtEntry:z.number().finite().min(0).max(100),checklistWarningsAtEntry:z.array(warning),createdAt:z.string(),closedAt:z.string().optional(),sellPrice:z.number().finite().positive().optional(),realizedPnL:z.number().finite().optional(),realizedReturnPercent:z.number().finite().optional(),target:z.number().finite().optional(),maxLoss:z.number().finite().optional(),invalidation:z.string().optional(),holding:z.string().optional(),closed:z.boolean().optional()});
const transaction=z.object({id:z.string().min(1),tradeId:z.number().int(),type:z.enum(["buy","sell"]),ticker,price:z.number().finite().positive(),shares:z.number().finite().positive(),amount:z.number().finite().positive(),occurredAt:z.string()});
const journal=z.object({tradeId:z.number().int(),buyReason:z.string(),sellReason:z.string(),emotionalState:z.string(),whatWentWell:z.string(),whatWentWrong:z.string(),thesisCorrect:z.string(),processCorrect:z.string(),lessonsLearned:z.string(),mistakeCategories:z.array(z.string())});
export const userDataV1Schema=z.object({version:z.literal(1),watchlist:z.array(watchlist),trades:z.array(v1Trade),checklistDrafts:z.record(ticker,checklist).default({}),journals:z.record(z.string(),journal).default({})});
const account=z.object({initialCash:z.number().finite().nonnegative(),cashBalance:z.number().finite().nonnegative(),transactions:z.array(transaction)}).superRefine((value,ctx)=>{
  const ids=new Set<string>(); const soldTrades=new Set<number>();
  value.transactions.forEach((tx,index)=>{if(ids.has(tx.id))ctx.addIssue({code:z.ZodIssueCode.custom,path:["transactions",index,"id"],message:"Duplicate transaction id"});ids.add(tx.id);if(tx.type==="sell"){if(soldTrades.has(tx.tradeId))ctx.addIssue({code:z.ZodIssueCode.custom,path:["transactions",index],message:"A trade can only be sold once"});soldTrades.add(tx.tradeId)}const expected=tx.type==="buy"?calculatePurchaseCost(tx.price,tx.shares):calculateSaleProceeds(tx.price,tx.shares);if(Math.abs(expected-tx.amount)>.005)ctx.addIssue({code:z.ZodIssueCode.custom,path:["transactions",index,"amount"],message:"Transaction amount does not match price times shares"})});
  if(Math.abs(calculateAvailableCash(value.initialCash,value.transactions)-value.cashBalance)>.005)ctx.addIssue({code:z.ZodIssueCode.custom,path:["cashBalance"],message:"Cash balance does not match the transaction ledger"});
});
export const userDataSchema=z.object({version:z.literal(2),account,watchlist:z.array(watchlist),trades:z.array(trade),checklistDrafts:z.record(ticker,checklist).default({}),journals:z.record(z.string(),journal).default({})}).superRefine((value,ctx)=>{
  const tradeIds=new Set<number>();value.trades.forEach((item,index)=>{if(tradeIds.has(item.id))ctx.addIssue({code:z.ZodIssueCode.custom,path:["trades",index,"id"],message:"Duplicate trade id"});tradeIds.add(item.id);const transactions=value.account.transactions.filter(tx=>tx.tradeId===item.id);if(transactions.filter(tx=>tx.type==="buy").length!==1)ctx.addIssue({code:z.ZodIssueCode.custom,path:["trades",index],message:"Each trade must have one buy transaction"});if(item.sellPrice&&transactions.filter(tx=>tx.type==="sell").length!==1)ctx.addIssue({code:z.ZodIssueCode.custom,path:["trades",index],message:"A sold trade must have one sell transaction"})});value.account.transactions.forEach((tx,index)=>{if(!tradeIds.has(tx.tradeId))ctx.addIssue({code:z.ZodIssueCode.custom,path:["account","transactions",index],message:"Transaction references an unknown trade"})});
});

export function emptyUserData(initialCash=25000):UserData{return{version:2,account:{initialCash,cashBalance:initialCash,transactions:[]},watchlist:[],trades:[],checklistDrafts:{},journals:{}}}

export function migrateV1ToV2(input:UserDataV1):UserData{
  const finalLegacyCash=6000;
  const trades:TradeRecord[]=input.trades.map(old=>{const realizedPnL=old.closed&&old.sellPrice?calculateRealizedPnL(old.buyPrice,old.sellPrice,old.shares):undefined;return{id:old.id,ticker:old.ticker,buyPrice:old.buyPrice,shares:old.shares,date:old.date,intendedWeightPercent:0,actualWeightPercentAtEntry:0,buyDriver:"Migrated from v1",upcomingEventStatus:"Unknown",targetPrice:old.target>0?old.target:old.buyPrice,maximumLossPercent:old.maxLoss>0&&old.maxLoss<=100?old.maxLoss:10,thesis:old.thesis,invalidationCondition:old.invalidation,exitPlan:"Reassess using the saved invalidation condition.",expectedHoldingPeriod:old.holding,checklistScoreAtEntry:0,checklistWarningsAtEntry:[],createdAt:`${old.date}T12:00:00.000Z`,closed:old.closed,closedAt:old.closed?`${old.date}T12:00:00.000Z`:undefined,sellPrice:old.sellPrice,realizedPnL,realizedReturnPercent:realizedPnL===undefined?undefined:realizedPnL/calculatePurchaseCost(old.buyPrice,old.shares)*100,target:old.target,maxLoss:old.maxLoss,invalidation:old.invalidation,holding:old.holding}});
  const transactions=trades.flatMap(trade=>{const buy={id:`buy-${trade.id}`,tradeId:trade.id,type:"buy" as const,ticker:trade.ticker,price:trade.buyPrice,shares:trade.shares,amount:calculatePurchaseCost(trade.buyPrice,trade.shares),occurredAt:trade.createdAt};return trade.closedAt&&trade.sellPrice?[buy,{id:`sell-${trade.id}`,tradeId:trade.id,type:"sell" as const,ticker:trade.ticker,price:trade.sellPrice,shares:trade.shares,amount:calculateSaleProceeds(trade.sellPrice,trade.shares),occurredAt:trade.closedAt}]:[buy]});
  const netOutflow=roundMoney(transactions.reduce((sum,tx)=>sum+(tx.type==="buy"?tx.amount:-tx.amount),0));
  const initialCash=Math.max(0,roundMoney(finalLegacyCash+netOutflow));
  return{version:2,account:{initialCash,cashBalance:calculateAvailableCash(initialCash,transactions),transactions},watchlist:input.watchlist,trades,checklistDrafts:input.checklistDrafts,journals:input.journals};
}

export function getBrowserStorage():Storage|undefined{try{return typeof window==="undefined"?undefined:window.localStorage}catch{return undefined}}
export function readThemePreference(storage?:Storage):"light"|"dark"{try{return storage?.getItem(THEME_STORAGE_KEY)==="dark"?"dark":"light"}catch{return"light"}}
export function writeThemePreference(theme:"light"|"dark",storage?:Storage):boolean{try{storage?.setItem(THEME_STORAGE_KEY,theme);return Boolean(storage)}catch{return false}}
export function readUserData(storage?:Storage):{data:UserData;recovered:boolean;hasSavedData:boolean;migrated:boolean}{
  if(!storage)return{data:emptyUserData(),recovered:false,hasSavedData:false,migrated:false};
  try{const current=storage.getItem(USER_DATA_STORAGE_KEY);if(current){try{const parsed=userDataSchema.safeParse(JSON.parse(current));if(parsed.success)return{data:parsed.data as UserData,recovered:false,hasSavedData:true,migrated:false}}catch{/* Fall through to a valid legacy record when available. */}}
    const legacy=storage.getItem(LEGACY_USER_DATA_STORAGE_KEY);if(!legacy)return{data:emptyUserData(),recovered:Boolean(current),hasSavedData:Boolean(current),migrated:false};const parsed=userDataV1Schema.safeParse(JSON.parse(legacy));if(!parsed.success)return{data:emptyUserData(),recovered:true,hasSavedData:true,migrated:false};const migrated=userDataSchema.safeParse(migrateV1ToV2(parsed.data as UserDataV1));if(!migrated.success)return{data:emptyUserData(),recovered:true,hasSavedData:true,migrated:false};const data=migrated.data as UserData;if(!writeUserData(data,storage))return{data,recovered:true,hasSavedData:true,migrated:false};return{data,recovered:Boolean(current),hasSavedData:true,migrated:true};
  }catch{return{data:emptyUserData(),recovered:true,hasSavedData:true,migrated:false}}
}
export function writeUserData(data:UserData,storage?:Storage):boolean{if(!storage)return false;const parsed=userDataSchema.safeParse(data);if(!parsed.success)return false;try{storage.setItem(USER_DATA_STORAGE_KEY,JSON.stringify(parsed.data));return true}catch{return false}}
